//! `ccform import`: evaluates `ccform.lua` (with any existing `import.lua`
//! overlay auto-merged in, mirroring what the next `plan`/`apply` would see)
//! as desired state, reads `~/.claude/settings.json` and the `mcpServers`
//! key of `~/.claude.json` as actual state, and writes whichever entries
//! exist only in actual back out as a freshly (re)generated
//! `~/.config/ccform/import.lua`.

use std::collections::HashMap;

use mlua::Value as LuaValue;
use serde_json::{Map, Value};

use crate::config::loader;
use crate::config::lua::Runtime;
use crate::config::lua_json::lua_to_json;
use crate::config::serialize_lua;
use crate::io::atomic;
use crate::paths;
use crate::state::diff::{Change, compute_diff};
use crate::target::mcp_servers::McpServers;
use crate::target::settings::Settings;

const HEADER: &str = "AUTO-GENERATED by `ccform import`. Edit at your own risk.\nPromote entries to base.lua / profiles/ and re-run `ccform import` to clean up.";

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error(transparent)]
    Lua(#[from] mlua::Error),

    #[error(transparent)]
    Loader(#[from] loader::Error),

    #[error(transparent)]
    Settings(#[from] crate::target::settings::Error),

    #[error(transparent)]
    McpServers(#[from] crate::target::mcp_servers::Error),

    #[error(transparent)]
    Write(#[from] atomic::Error),
}

pub type Result<T> = std::result::Result<T, Error>;

/// Computes desired-vs-actual for `settings` and `mcpServers`, collects the
/// entries that exist only in actual, and overwrites
/// `~/.config/ccform/import.lua` with them as a Lua table literal. Leaves
/// `state.json` untouched.
pub fn run() -> Result<()> {
    let config_dir = paths::config_dir();
    let runtime = Runtime::new(&config_dir)?;

    let entry_value = runtime.load_entry(&paths::entry_path())?;
    let root = loader::validate_root(entry_value)?;
    let root = runtime.maybe_apply_import_overlay(root, &paths::import_path())?;
    let (desired, _meta) = loader::partition_root(runtime.lua(), root)?;
    let desired_settings = lua_to_json(&LuaValue::Table(desired.settings))?;
    let desired_mcp_servers = lua_to_json(&LuaValue::Table(desired.mcp_servers))?;

    let actual_settings = Settings::new(paths::settings_path()).read()?;
    let actual_mcp_servers = McpServers::from_home().read()?;
    // McpServers::read() reports a missing file or key as `Value::Null`, not
    // an empty object, since callers other than `import` need to tell
    // "absent" from "explicitly empty".
    let actual_mcp_servers = if actual_mcp_servers.is_null() {
        Value::Object(Map::new())
    } else {
        actual_mcp_servers
    };

    let settings_candidates =
        compute_diff(None, &actual_settings, &desired_settings).import_candidates;
    let mcp_servers_candidates =
        compute_diff(None, &actual_mcp_servers, &desired_mcp_servers).import_candidates;

    let mut out = Map::new();
    let settings_tree = tree_from_changes(&settings_candidates);
    if !is_empty_object(&settings_tree) {
        out.insert("settings".to_string(), settings_tree);
    }
    let mcp_servers_tree = tree_from_changes(&mcp_servers_candidates);
    if !is_empty_object(&mcp_servers_tree) {
        out.insert("mcpServers".to_string(), mcp_servers_tree);
    }

    let lua_source = serialize_lua::to_lua_literal(&Value::Object(out), Some(HEADER));

    atomic::ensure_dir(&config_dir, 0o700)?;
    atomic::write_bytes(&paths::import_path(), lua_source.as_bytes(), 0o600)?;

    Ok(())
}

fn is_empty_object(value: &Value) -> bool {
    matches!(value, Value::Object(map) if map.is_empty())
}

/// Rebuilds a JSON tree from `changes`' RFC 6901 pointer paths and values, as
/// produced by [`compute_diff`]'s `import_candidates`: a flat list of
/// `Add`-kind leaves, each carrying the value of an entire new subtree
/// (`compute_diff` never recurses past a path it has already reported as
/// added). A path segment made only of ASCII digits addresses an array
/// element; anything else addresses an object key.
///
/// Array elements are appended in the order their changes are visited
/// rather than placed at their original numeric index: `ccform.merge`
/// concatenates arrays instead of merging them by index, so the original
/// position has no meaning once this tree is merged back into `desired` on
/// the next `plan`/`apply` — only that every element ends up present.
/// Multiple changes that share an original array index (e.g. two new keys
/// added to the same existing element) fold into one appended element
/// rather than becoming one appended element each.
fn tree_from_changes(changes: &[Change]) -> Value {
    let mut root = Value::Object(Map::new());
    let mut array_slots: HashMap<&str, usize> = HashMap::new();
    for change in changes {
        let Some(value) = change.after.clone() else {
            unreachable!("import candidates are Add changes, which always carry an `after` value");
        };
        insert(&mut root, &change.path, value, &mut array_slots);
    }
    root
}

fn insert<'a>(
    root: &mut Value,
    path: &'a str,
    value: Value,
    array_slots: &mut HashMap<&'a str, usize>,
) {
    let tokens: Vec<&str> = path.split('/').skip(1).collect();
    let mut node = root;
    let mut consumed = 0usize;
    for (i, token) in tokens.iter().enumerate() {
        consumed += 1 + token.len();
        let is_last = i + 1 == tokens.len();

        node = if is_array_index(token) {
            let array = as_array_mut(node);
            let slot = *array_slots.entry(&path[..consumed]).or_insert_with(|| {
                array.push(Value::Null);
                array.len() - 1
            });
            &mut array[slot]
        } else {
            as_object_mut(node)
                .entry(unescape_token(token))
                .or_insert(Value::Null)
        };

        if is_last {
            *node = value;
            return;
        }
    }
}

fn as_object_mut(value: &mut Value) -> &mut Map<String, Value> {
    if !value.is_object() {
        *value = Value::Object(Map::new());
    }
    let Value::Object(map) = value else {
        unreachable!("just replaced value with Value::Object above");
    };
    map
}

fn as_array_mut(value: &mut Value) -> &mut Vec<Value> {
    if !value.is_array() {
        *value = Value::Array(Vec::new());
    }
    let Value::Array(items) = value else {
        unreachable!("just replaced value with Value::Array above");
    };
    items
}

/// An RFC 6901 pointer segment made only of ASCII digits addresses an array
/// element (matching how `state::diff::compute_diff` always renders array
/// indices as plain decimal strings); anything else addresses an object key.
fn is_array_index(token: &str) -> bool {
    !token.is_empty() && token.bytes().all(|b| b.is_ascii_digit())
}

/// Reverses RFC 6901 escaping: `~1` back to `/`, then `~0` back to `~`, in
/// that order since escaping applies them in the opposite sequence.
fn unescape_token(token: &str) -> String {
    token.replace("~1", "/").replace("~0", "~")
}

#[cfg(test)]
mod tests {
    use rstest::rstest;
    use serde_json::json;

    use super::*;

    #[rstest]
    #[case::no_changes_yields_an_empty_object(vec![], json!({}))]
    #[case::builds_nested_objects_from_pointer_segments(
        vec![Change::add("/permissions/allow", json!(["Bash(brew:*)"]))],
        json!({"permissions": {"allow": ["Bash(brew:*)"]}})
    )]
    #[case::multiple_changes_populate_sibling_keys(
        vec![
            Change::add("/model", json!("opus")),
            Change::add("/permissions/deny", json!(["Bash(rm:*)"])),
        ],
        json!({"model": "opus", "permissions": {"deny": ["Bash(rm:*)"]}})
    )]
    #[case::array_elements_are_appended_in_visited_order(
        vec![
            Change::add("/allow/0", json!("a")),
            Change::add("/allow/1", json!("b")),
        ],
        json!({"allow": ["a", "b"]})
    )]
    #[case::changes_sharing_an_original_array_index_fold_into_one_element(
        vec![
            Change::add("/list/0/y", json!(2)),
            Change::add("/list/0/z", json!(3)),
        ],
        json!({"list": [{"y": 2, "z": 3}]})
    )]
    #[case::tilde_and_slash_pointer_tokens_are_unescaped(
        vec![Change::add("/a~1b~0c", json!(1))],
        json!({"a/b~c": 1})
    )]
    fn test_tree_from_changes(#[case] changes: Vec<Change>, #[case] expected: Value) {
        assert_eq!(tree_from_changes(&changes), expected);
    }
}
