//! `ccform init`: reads the current `~/.claude/settings.json` and the
//! `mcpServers` key of `~/.claude.json`, writes them out as a `ccform.lua`
//! bootstrap, and initializes `state.json` with the same content so the next
//! `ccform plan` has something to diff against.

use std::path::PathBuf;

use serde_json::{Map, Value};

use crate::config::serialize_lua;
use crate::io::atomic;
use crate::paths;
use crate::state::store::{self, State};
use crate::target::mcp_servers::McpServers;
use crate::target::settings::Settings;

const HEADER: &str = "Generated by `ccform init`. You can edit this file freely.\nSplit into base.lua / profiles/*.lua and `require` them as needed.";

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("{path} already exists. Use --force to overwrite.")]
    AlreadyExists { path: PathBuf },

    #[error(transparent)]
    Settings(#[from] crate::target::settings::Error),

    #[error(transparent)]
    McpServers(#[from] crate::target::mcp_servers::Error),

    #[error(transparent)]
    Write(#[from] atomic::Error),

    #[error(transparent)]
    State(#[from] store::Error),
}

pub type Result<T> = std::result::Result<T, Error>;

/// Bootstraps `ccform.lua` and `state.json` from whatever is currently on
/// disk. Fails with [`Error::AlreadyExists`] if `ccform.lua` is already
/// present, unless `force` is set.
pub fn run(force: bool) -> Result<()> {
    let entry_path = paths::entry_path();
    if entry_path.exists() && !force {
        return Err(Error::AlreadyExists { path: entry_path });
    }

    let settings = Settings::new(paths::settings_path()).read()?;
    let mcp_servers = McpServers::from_home().read()?;
    // McpServers::read() reports a missing file or key as `Value::Null`, not
    // an empty object, since callers other than `init` need to tell "absent"
    // from "explicitly empty".
    let mcp_servers = if mcp_servers.is_null() {
        Value::Object(Map::new())
    } else {
        mcp_servers
    };

    let mut bootstrap = Map::new();
    bootstrap.insert("settings".to_string(), settings.clone());
    bootstrap.insert("mcpServers".to_string(), mcp_servers.clone());
    let lua_source = serialize_lua::to_lua_literal(&Value::Object(bootstrap), Some(HEADER));

    atomic::ensure_dir(&paths::config_dir(), 0o700)?;
    atomic::write_bytes(&entry_path, lua_source.as_bytes(), 0o600)?;

    store::initialize(&State {
        version: 1,
        settings,
        mcp_servers,
    })?;

    Ok(())
}
