//! End-to-end checks for `ccform import` against a temporary `$HOME` and XDG
//! directories, so the real user's `~/.claude/settings.json` /
//! `~/.config/ccform/` are never touched.

use std::fs;
use std::path::PathBuf;
use std::process::{Command, Output};

use indoc::indoc;
use rstest::{fixture, rstest};
use tempfile::TempDir;

// `#[cfg(test)]` below isn't conditional compilation — this whole file is
// already only built for `cargo test` — it's there so clippy's
// `allow-unwrap-in-tests` recognizes the `unwrap()` calls as test code:
// that check looks for the attribute on an enclosing item, and rstest's
// `#[fixture]` macro regenerates the function it wraps and drops any
// attribute it doesn't itself recognize, which is why `new_env` is a plain
// function the `env` fixture delegates to rather than being annotated
// directly.
#[cfg(test)]
struct Env {
    home: TempDir,
    config: TempDir,
    state: TempDir,
}

#[cfg(test)]
impl Env {
    fn run(&self, args: &[&str]) -> Output {
        Command::new(env!("CARGO_BIN_EXE_ccform"))
            .args(args)
            .env("HOME", self.home.path())
            .env("XDG_CONFIG_HOME", self.config.path())
            .env("XDG_STATE_HOME", self.state.path())
            .output()
            .unwrap()
    }

    fn write_entry_lua(&self, contents: &str) {
        let dir = self.config.path().join("ccform");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("ccform.lua"), contents).unwrap();
    }

    fn write_import_lua(&self, contents: &str) {
        let dir = self.config.path().join("ccform");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("import.lua"), contents).unwrap();
    }

    fn write_settings(&self, contents: &str) {
        let dir = self.home.path().join(".claude");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("settings.json"), contents).unwrap();
    }

    fn write_claude_json(&self, contents: &str) {
        fs::write(self.home.path().join(".claude.json"), contents).unwrap();
    }

    fn write_state(&self, contents: &str) {
        let dir = self.state.path().join("ccform");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("state.json"), contents).unwrap();
    }

    fn import_path(&self) -> PathBuf {
        self.config.path().join("ccform").join("import.lua")
    }

    fn state_path(&self) -> PathBuf {
        self.state.path().join("ccform").join("state.json")
    }

    fn read_import_lua(&self) -> String {
        fs::read_to_string(self.import_path()).unwrap()
    }
}

#[cfg(test)]
fn new_env() -> Env {
    Env {
        home: tempfile::tempdir().unwrap(),
        config: tempfile::tempdir().unwrap(),
        state: tempfile::tempdir().unwrap(),
    }
}

#[fixture]
fn env() -> Env {
    new_env()
}

#[rstest]
#[case::settings_drift_only(
    "return { settings = { model = 'opus' } }",
    r#"{"model":"opus","extraField":true}"#,
    None,
    indoc! {"
        -- AUTO-GENERATED by `ccform import`. Edit at your own risk.
        -- Promote entries to base.lua / profiles/ and re-run `ccform import` to clean up.
        return {
          settings = {
            extraField = true,
          },
        }
    "}
)]
#[case::settings_and_mcp_servers_drift(
    "return { settings = { model = 'opus' }, mcpServers = { context7 = {} } }",
    r#"{"model":"opus","extraField":true}"#,
    Some(r#"{"mcpServers":{"context7":{},"foo":{"command":"bar"}}}"#),
    indoc! {"
        -- AUTO-GENERATED by `ccform import`. Edit at your own risk.
        -- Promote entries to base.lua / profiles/ and re-run `ccform import` to clean up.
        return {
          settings = {
            extraField = true,
          },
          mcpServers = {
            foo = {
              command = 'bar',
            },
          },
        }
    "}
)]
#[case::mcp_servers_drift_only(
    "return { settings = { model = 'opus' }, mcpServers = { context7 = {} } }",
    r#"{"model":"opus"}"#,
    Some(r#"{"mcpServers":{"context7":{},"foo":{"command":"bar"}}}"#),
    indoc! {"
        -- AUTO-GENERATED by `ccform import`. Edit at your own risk.
        -- Promote entries to base.lua / profiles/ and re-run `ccform import` to clean up.
        return {
          mcpServers = {
            foo = {
              command = 'bar',
            },
          },
        }
    "}
)]
#[case::no_drift(
    "return { settings = { model = 'opus' } }",
    r#"{"model":"opus"}"#,
    None,
    indoc! {"
        -- AUTO-GENERATED by `ccform import`. Edit at your own risk.
        -- Promote entries to base.lua / profiles/ and re-run `ccform import` to clean up.
        return {}
    "}
)]
fn writes_actual_only_entries_to_import_lua(
    env: Env,
    #[case] entry_lua: &str,
    #[case] settings: &str,
    #[case] claude_json: Option<&str>,
    #[case] expected_import_lua: &str,
) {
    env.write_entry_lua(entry_lua);
    env.write_settings(settings);
    if let Some(contents) = claude_json {
        env.write_claude_json(contents);
    }

    let output = env.run(&["import"]);

    assert_eq!(output.status.code(), Some(0));
    assert_eq!(env.read_import_lua(), expected_import_lua);
}

#[rstest]
fn import_lua_is_regenerated_from_scratch_each_run(env: Env) {
    env.write_entry_lua("return { settings = { model = 'opus' } }");
    env.write_import_lua("-- old\nreturn { settings = { staleField = 'stale' } }");
    env.write_settings(r#"{"model":"opus","newField":"value"}"#);

    let output = env.run(&["import"]);

    assert_eq!(output.status.code(), Some(0));
    assert_eq!(
        env.read_import_lua(),
        indoc! {"
            -- AUTO-GENERATED by `ccform import`. Edit at your own risk.
            -- Promote entries to base.lua / profiles/ and re-run `ccform import` to clean up.
            return {
              settings = {
                newField = 'value',
              },
            }
        "}
    );
}

#[rstest]
fn does_not_modify_state_json(env: Env) {
    env.write_entry_lua("return { settings = { model = 'opus' } }");
    env.write_settings(r#"{"model":"opus","extraField":true}"#);
    let state_contents = r#"{"version":1,"settings":{"model":"opus"},"mcpServers":{}}"#;
    env.write_state(state_contents);

    let output = env.run(&["import"]);

    assert_eq!(output.status.code(), Some(0));
    assert_eq!(
        fs::read_to_string(env.state_path()).unwrap(),
        state_contents
    );
}
