//! End-to-end checks for `ccform init` against a temporary `$HOME` and XDG
//! directories, so the real user's `~/.claude/settings.json` /
//! `~/.config/ccform/ccform.lua` are never touched.

use std::fs;
use std::path::PathBuf;
use std::process::Output;

use indoc::indoc;
use rstest::rstest;
use serde_json::{Value, json};

mod common;
use common::{Env, env};

const EXISTING_CCFORM_LUA: &str = indoc! {"
    -- existing
    return {}
"};

// See the equivalent comment in tests/common/mod.rs for why this needs
// `#[cfg(test)]` despite the whole file already being test-only.
#[cfg(test)]
impl Env {
    fn write_settings(&self, contents: &str) {
        let dir = self.home.path().join(".claude");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("settings.json"), contents).unwrap();
    }

    fn write_claude_json(&self, contents: &str) {
        fs::write(self.home.path().join(".claude.json"), contents).unwrap();
    }

    fn entry_path(&self) -> PathBuf {
        self.config.path().join("ccform").join("ccform.lua")
    }

    fn read_state(&self) -> Value {
        serde_json::from_str(&fs::read_to_string(self.state_path()).unwrap()).unwrap()
    }
}

#[cfg(test)]
fn assert_bootstrap_succeeded(
    env: &Env,
    output: &Output,
    expected_lua: &str,
    expected_state: &Value,
) {
    assert_eq!(output.status.code(), Some(0));
    assert_eq!(fs::read_to_string(env.entry_path()).unwrap(), expected_lua);
    assert_eq!(&env.read_state(), expected_state);
}

#[rstest]
#[case::existing_settings_and_mcp_servers(
    Some(r#"{"model":"opus"}"#),
    Some(r#"{"mcpServers":{"foo":{"command":"bar"}},"oauthAccount":{"email":"user@example.com"}}"#),
    indoc! {"
        -- Generated by `ccform init`. You can edit this file freely.
        -- Split into base.lua / profiles/*.lua and `require` them as needed.
        return {
          settings = {
            model = 'opus',
          },
          mcpServers = {
            foo = {
              command = 'bar',
            },
          },
        }
    "},
    json!({
        "version": 1,
        "settings": {"model": "opus"},
        "mcpServers": {"foo": {"command": "bar"}},
    })
)]
#[case::settings_and_claude_json_missing(
    None,
    None,
    indoc! {"
        -- Generated by `ccform init`. You can edit this file freely.
        -- Split into base.lua / profiles/*.lua and `require` them as needed.
        return {
          settings = {},
          mcpServers = {},
        }
    "},
    json!({"version": 1, "settings": {}, "mcpServers": {}})
)]
fn bootstraps_ccform_lua_and_state_json_from_current_settings(
    env: Env,
    #[case] settings: Option<&str>,
    #[case] claude_json: Option<&str>,
    #[case] expected_lua: &str,
    #[case] expected_state: Value,
) {
    if let Some(contents) = settings {
        env.write_settings(contents);
    }
    if let Some(contents) = claude_json {
        env.write_claude_json(contents);
    }

    let output = env.run(&["init"]);

    assert_bootstrap_succeeded(&env, &output, expected_lua, &expected_state);
}

#[rstest]
fn rejects_overwriting_an_existing_ccform_lua_without_force(env: Env) {
    fs::create_dir_all(env.entry_path().parent().unwrap()).unwrap();
    fs::write(env.entry_path(), EXISTING_CCFORM_LUA).unwrap();

    let output = env.run(&["init"]);

    assert_eq!(output.status.code(), Some(3));
    assert_eq!(
        String::from_utf8(output.stderr).unwrap(),
        format!(
            "Error: {} already exists. Use --force to overwrite.\n",
            env.entry_path().display()
        )
    );
    assert_eq!(
        fs::read_to_string(env.entry_path()).unwrap(),
        EXISTING_CCFORM_LUA
    );
    assert!(!env.state_path().exists());
}

#[rstest]
fn rejects_overwriting_an_existing_state_json_without_force(env: Env) {
    fs::create_dir_all(env.state_path().parent().unwrap()).unwrap();
    fs::write(
        env.state_path(),
        r#"{"version":1,"settings":{"model":"opus"},"mcpServers":{}}"#,
    )
    .unwrap();

    let output = env.run(&["init"]);

    assert_eq!(output.status.code(), Some(3));
    assert_eq!(
        String::from_utf8(output.stderr).unwrap(),
        format!(
            "Error: {} already exists. Use --force to overwrite.\n",
            env.state_path().display()
        )
    );
    assert_eq!(
        env.read_state(),
        json!({"version": 1, "settings": {"model": "opus"}, "mcpServers": {}})
    );
    assert!(!env.entry_path().exists());
}

#[rstest]
fn force_overwrites_an_existing_ccform_lua_and_state_json(env: Env) {
    fs::create_dir_all(env.entry_path().parent().unwrap()).unwrap();
    fs::write(env.entry_path(), EXISTING_CCFORM_LUA).unwrap();
    env.write_settings(r#"{"model":"opus"}"#);

    let output = env.run(&["init", "--force"]);

    assert_bootstrap_succeeded(
        &env,
        &output,
        indoc! {"
            -- Generated by `ccform init`. You can edit this file freely.
            -- Split into base.lua / profiles/*.lua and `require` them as needed.
            return {
              settings = {
                model = 'opus',
              },
              mcpServers = {},
            }
        "},
        &json!({"version": 1, "settings": {"model": "opus"}, "mcpServers": {}}),
    );
}
