//! End-to-end checks for `ccform init` against a temporary `$HOME` and XDG
//! directories, so the real user's `~/.claude/settings.json` /
//! `~/.config/ccform/ccform.lua` are never touched.

use std::fs;
use std::path::PathBuf;
use std::process::{Command, Output};

use indoc::indoc;
use rstest::{fixture, rstest};
use serde_json::{Value, json};
use tempfile::TempDir;

const EXISTING_CCFORM_LUA: &str = indoc! {"
    -- existing
    return {}
"};

#[cfg(test)]
struct Env {
    home: TempDir,
    config: TempDir,
    state: TempDir,
}

#[cfg(test)]
impl Env {
    fn run(&self, args: &[&str]) -> Output {
        Command::new(env!("CARGO_BIN_EXE_ccform"))
            .args(args)
            .env("HOME", self.home.path())
            .env("XDG_CONFIG_HOME", self.config.path())
            .env("XDG_STATE_HOME", self.state.path())
            .output()
            .unwrap()
    }

    fn write_settings(&self, contents: &str) {
        let dir = self.home.path().join(".claude");
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("settings.json"), contents).unwrap();
    }

    fn write_claude_json(&self, contents: &str) {
        fs::write(self.home.path().join(".claude.json"), contents).unwrap();
    }

    fn entry_path(&self) -> PathBuf {
        self.config.path().join("ccform").join("ccform.lua")
    }

    fn state_path(&self) -> PathBuf {
        self.state.path().join("ccform").join("state.json")
    }

    fn read_state(&self) -> Value {
        serde_json::from_str(&fs::read_to_string(self.state_path()).unwrap()).unwrap()
    }
}

#[cfg(test)]
fn new_env() -> Env {
    Env {
        home: tempfile::tempdir().unwrap(),
        config: tempfile::tempdir().unwrap(),
        state: tempfile::tempdir().unwrap(),
    }
}

#[fixture]
fn env() -> Env {
    new_env()
}

#[rstest]
fn bootstraps_ccform_lua_and_state_json_from_existing_settings(env: Env) {
    env.write_settings(r#"{"model":"opus"}"#);
    env.write_claude_json(
        r#"{"mcpServers":{"foo":{"command":"bar"}},"oauthAccount":{"email":"user@example.com"}}"#,
    );

    let output = env.run(&["init"]);

    assert_eq!(output.status.code(), Some(0));
    assert_eq!(
        fs::read_to_string(env.entry_path()).unwrap(),
        indoc! {"
            -- Generated by `ccform init`. You can edit this file freely.
            -- Split into base.lua / profiles/*.lua and `require` them as needed.
            return {
              settings = {
                model = 'opus',
              },
              mcpServers = {
                foo = {
                  command = 'bar',
                },
              },
            }
        "}
    );
    assert_eq!(
        env.read_state(),
        json!({
            "version": 1,
            "settings": {"model": "opus"},
            "mcpServers": {"foo": {"command": "bar"}},
        })
    );
}

#[rstest]
fn bootstraps_empty_tables_when_settings_and_claude_json_are_missing(env: Env) {
    let output = env.run(&["init"]);

    assert_eq!(output.status.code(), Some(0));
    assert_eq!(
        fs::read_to_string(env.entry_path()).unwrap(),
        indoc! {"
            -- Generated by `ccform init`. You can edit this file freely.
            -- Split into base.lua / profiles/*.lua and `require` them as needed.
            return {
              settings = {},
              mcpServers = {},
            }
        "}
    );
    assert_eq!(
        env.read_state(),
        json!({"version": 1, "settings": {}, "mcpServers": {}})
    );
}

#[rstest]
fn rejects_overwriting_an_existing_ccform_lua_without_force(env: Env) {
    fs::create_dir_all(env.entry_path().parent().unwrap()).unwrap();
    fs::write(env.entry_path(), EXISTING_CCFORM_LUA).unwrap();

    let output = env.run(&["init"]);

    assert_eq!(output.status.code(), Some(3));
    assert_eq!(
        String::from_utf8(output.stderr).unwrap(),
        format!(
            "Error: {} already exists. Use --force to overwrite.\n",
            env.entry_path().display()
        )
    );
    assert_eq!(
        fs::read_to_string(env.entry_path()).unwrap(),
        EXISTING_CCFORM_LUA
    );
    assert!(!env.state_path().exists());
}

#[rstest]
fn rejects_overwriting_an_existing_state_json_without_force(env: Env) {
    fs::create_dir_all(env.state_path().parent().unwrap()).unwrap();
    fs::write(
        env.state_path(),
        r#"{"version":1,"settings":{"model":"opus"},"mcpServers":{}}"#,
    )
    .unwrap();

    let output = env.run(&["init"]);

    assert_eq!(output.status.code(), Some(3));
    assert_eq!(
        String::from_utf8(output.stderr).unwrap(),
        format!(
            "Error: {} already exists. Use --force to overwrite.\n",
            env.state_path().display()
        )
    );
    assert_eq!(
        env.read_state(),
        json!({"version": 1, "settings": {"model": "opus"}, "mcpServers": {}})
    );
    assert!(!env.entry_path().exists());
}

#[rstest]
fn force_overwrites_an_existing_ccform_lua_and_state_json(env: Env) {
    fs::create_dir_all(env.entry_path().parent().unwrap()).unwrap();
    fs::write(env.entry_path(), EXISTING_CCFORM_LUA).unwrap();
    env.write_settings(r#"{"model":"opus"}"#);

    let output = env.run(&["init", "--force"]);

    assert_eq!(output.status.code(), Some(0));
    assert_eq!(
        fs::read_to_string(env.entry_path()).unwrap(),
        indoc! {"
            -- Generated by `ccform init`. You can edit this file freely.
            -- Split into base.lua / profiles/*.lua and `require` them as needed.
            return {
              settings = {
                model = 'opus',
              },
              mcpServers = {},
            }
        "}
    );
    assert_eq!(
        env.read_state(),
        json!({"version": 1, "settings": {"model": "opus"}, "mcpServers": {}})
    );
}
